INSERT INTO user_search_sets (set_name, 
company_name, 
ticker, 
filing_period, 
trade_period, 
is_purchase, 
is_sale, 
trade_min, 
trade_max, 
is_officer, 
is_director, 
is_ten_percent, 
group_by, 
sort_by,
is_tracked) VALUES (
"Top 10 NASDAQ stocks",
 "",
 "AAPL MSFT AMZN TSLA NVDA GOOG FB NFLX INTC CSCO",
 1, 3, 0, 1, "", "", 1, 1, 1, 0, 3, 1)