INSERT INTO search_set (set_name, 
company_name, 
ticker, 
filing_period, 
trade_period, 
is_purchase, 
is_sale, 
trade_min, 
trade_max, 
is_officer, 
is_director, 
is_ten_percent, 
group_by, 
sort_by,
target) VALUES ("Test entry2", "", "", 5, 5, 0, 1, "9999", "", 1, 1, 1, 0, 3, "tracking")