INSERT INTO search_set (
set_name, 
company_name, 
ticker, 
filing_period, 
trade_period, 
is_purchase, 
is_sale, 
trade_min, 
trade_max, 
is_officer, 
is_director, 
is_ten_percent, 
group_by, 
sort_by,
target,
is_tracked,
is_default) VALUES (
"Dow Jones top 30 stocks",
 "",
 "AXP AMGN AAPL BA CAT CSCO CVX GS HD HON IBM INTC JNJ KO JPM MCD MMM MRK MSFT NKE PG TRV UNH CRM VZ V WBA WMT DIS DOW",
 1, 3, 1, 0, "", "", 1, 1, 1, 0, 3, "tracking", 1, 1)